In [3]:
import tensorflow as tf

In [4]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 9s 1us/step


In [6]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Input((28, 28)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [7]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.1990737 ,  0.92283726,  0.46733832, -0.23873413,  0.20877257,
        -0.8422064 , -0.33485126, -0.38923126,  0.88790494, -0.37670472]],
      dtype=float32)

In [8]:
tf.nn.softmax(predictions)

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[0.09927242, 0.20471758, 0.12981786, 0.06407537, 0.10023993,
        0.03504341, 0.05820334, 0.05512277, 0.19768977, 0.05581761]],
      dtype=float32)>

In [9]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [14]:
loss_fn(y_train[:1], predictions).numpy()

np.float32(3.3511677)

In [15]:
model.compile(optimizer='adam', loss=loss_fn, metrics=['accuracy'])

In [16]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 523us/step - accuracy: 0.9126 - loss: 0.2990
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 542us/step - accuracy: 0.9567 - loss: 0.1448
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 567us/step - accuracy: 0.9675 - loss: 0.1088
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 535us/step - accuracy: 0.9724 - loss: 0.0888
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 545us/step - accuracy: 0.9767 - loss: 0.0754


In [17]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - 405us/step - accuracy: 0.9774 - loss: 0.0730


[0.073033407330513, 0.977400004863739]